type Query {
    accountsList: [BankAccount]
    accountById(id: String): BankAccount
    customersList:[Customer]

}

type Mutation  {

    createaccount(bankAccount: BankAccountRequestDTO): BankAccount
    updateaccount(bankAccount: BankAccountRequestDTO,id:String): BankAccount
    deleteaccount(id:String):Boolean

}

type BankAccount {
    id: String
    createdAt: Float
    balance: Float
    currency: String
    accountType: String
    customer :Customer
}
type Customer {
    id: String
    name: String
    banckAccounts :[BankAccount]
}

input BankAccountRequestDTO {
    balance: Float
    currency: String
    accountType: String
}